x = input('Digite uma seu nome, sua idade, e uma cor: ')
print('O Nome esta correto? ', x.isalpha())
print('A idade esta correta? ', x.isnumeric())
print('A cor esta correta? ', x.isalpha())
print('O Tipo primitivo deste valor é: ', type(x))
print('O valor digitado foi: ', x)
print('Existe espaços neste valor? ', x.isspace())
print('Esta em maiusculas? ', x.isupper())
print('Esta em minusculas? ', x.islower())
print('Esta capitalizada? ', x.istitle())
